name: Tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.4, 8.5]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Composer dependencies
        working-directory: ./laravel
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Install NPM dependencies & Build Assets
        working-directory: ./laravel
        run: |
          npm install
          npm run build -- --manifest

      - name: Copy environment file
        working-directory: ./laravel
        run: cp .env.example .env

      - name: Generate app key
        working-directory: ./laravel
        run: php artisan key:generate

      - name: Execute tests
        working-directory: ./laravel
        run: php artisan test